"""initial

Revision ID: 063d3b72f005
Revises: 
Create Date: 2026-01-12 16:41:16.221177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '063d3b72f005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lieux',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('permissions', mysql.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_document', sa.String(length=255), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('nationalite', sa.String(length=255), nullable=True),
    sa.Column('date_de_naissance', sa.Date(), nullable=True),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('lieu_naissance', sa.String(length=255), nullable=True),
    sa.Column('date_de_delivrance', sa.Date(), nullable=True),
    sa.Column('date_d_expiration', sa.Date(), nullable=True),
    sa.Column('chemin_image', sa.Text(), nullable=True),
    sa.Column('taille', sa.Float(), nullable=True),
    sa.Column('poids', sa.Float(), nullable=True),
    sa.Column('profession', sa.String(length=255), nullable=True),
    sa.Column('domicile', sa.String(length=255), nullable=True),
    sa.Column('organisme_delivrance', sa.String(length=255), nullable=True),
    sa.Column('info_nfc', sa.String(length=255), nullable=True),
    sa.Column('type_document_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_document_id'], ['type_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('mot_passe', sa.String(length=255), nullable=True),
    sa.Column('poste', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_concerne_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_concerne_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('text_detected', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', sa.Text(), nullable=True),
    sa.Column('annotated_image', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_verification', sa.DateTime(), nullable=True),
    sa.Column('resultat_photo', sa.String(length=50), nullable=True),
    sa.Column('resultat_donnee', sa.String(length=50), nullable=True),
    sa.Column('url_image_echec', sa.String(length=255), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('lieu_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('ocr_result_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['lieu_id'], ['lieux.id'], ),
    sa.ForeignKeyConstraint(['ocr_result_id'], ['ocr_results.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verifications')
    op.drop_table('ocr_results')
    op.drop_table('notifications')
    op.drop_table('utilisateurs')
    op.drop_table('documents')
    op.drop_table('type_documents')
    op.drop_table('roles')
    op.drop_table('lieux')
    # ### end Alembic commands ###
